remote_theme: mikearnaldi/just-the-docs
search_enabled: true
aux_links:
  "Docs":
    - "//effect-ts.github.io/opentelemetry"
  "API Reference":
    - "//effect-ts.github.io/opentelemetry/docs/modules"
  "GitHub":
    - "//github.com/effect-ts/opentelemetry"
